# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dfabfb1fb6ac44cc330a040d52657e20"
name = "Product-GPT"
handle = "product-gpt"
application_url = "https://threshold-rebound-sie-in.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://threshold-rebound-sie-in.trycloudflare.com/auth/callback", "https://threshold-rebound-sie-in.trycloudflare.com/auth/shopify/callback", "https://threshold-rebound-sie-in.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
