# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dfabfb1fb6ac44cc330a040d52657e20"
name = "Product-GPT"
handle = "product-gpt"
application_url = "https://product-gpt-app-production.up.railway.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2023-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders"

[auth]
redirect_urls = ["https://product-gpt-app-production.up.railway.app/auth/callback", "https://product-gpt-app-production.up.railway.app/auth/shopify/callback", "https://product-gpt-app-production.up.railway.app/api/auth/callback"]

[pos]
embedded = false
