name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[build]
path = "."

[build.environment]
NODE_ENV = "development"

[dev]
command = "npm exec remix vite:dev"
